# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: compiler_service.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16\x63ompiler_service.proto\x12\nfscompiler\"g\n\x04\x66qir\x12\r\n\x05model\x18\x01 \x01(\x0c\x12\x16\n\tbatch_dim\x18\x02 \x01(\x03H\x00\x88\x01\x01\x12\x19\n\x0csequence_dim\x18\x03 \x01(\x03H\x01\x88\x01\x01\x42\x0c\n\n_batch_dimB\x0f\n\r_sequence_dim\"G\n\x06tflite\x12\r\n\x05model\x18\x01 \x01(\x0c\x12\x1b\n\x0esignature_name\x18\x02 \x01(\tH\x00\x88\x01\x01\x42\x11\n\x0f_signature_name\"U\n\x05model\x12 \n\x04\x66qir\x18\x01 \x01(\x0b\x32\x10.fscompiler.fqirH\x00\x12$\n\x06tflite\x18\x02 \x01(\x0b\x32\x12.fscompiler.tfliteH\x00\x42\x04\n\x02ir\"&\n\x06status\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0b\n\x03msg\x18\x02 \x01(\t\"I\n\x12\x63ompiled_artifacts\x12\x0f\n\x07\x62itfile\x18\x01 \x01(\x0c\x12\"\n\x06status\x18\x02 \x01(\x0b\x32\x12.fscompiler.status\"&\n\x07ndarray\x12\x0c\n\x04\x64\x61ta\x18\x01 \x03(\x02\x12\r\n\x05shape\x18\x02 \x03(\x03\"i\n\x0fsimulation_data\x12!\n\x04\x64\x61ta\x18\x01 \x03(\x0b\x32\x13.fscompiler.ndarray\x12\x17\n\x0fquantize_inputs\x18\x02 \x01(\x08\x12\x1a\n\x12\x64\x65quantize_outputs\x18\x03 \x01(\x08\"t\n\x10simulation_input\x12\"\n\x05model\x18\x01 \x01(\x0b\x32\x11.fscompiler.modelH\x00\x12+\n\x04\x64\x61ta\x18\x02 \x01(\x0b\x32\x1b.fscompiler.simulation_dataH\x00\x42\x0f\n\rmodel_or_data\"j\n\x11simulation_output\x12!\n\x04\x64\x61ta\x18\x01 \x03(\x0b\x32\x13.fscompiler.ndarray\x12\x0e\n\x06report\x18\x02 \x01(\t\x12\"\n\x06status\x18\x03 \x01(\x0b\x32\x12.fscompiler.status2\x98\x01\n\x07\x43ompile\x12>\n\x07\x63ompile\x12\x11.fscompiler.model\x1a\x1e.fscompiler.compiled_artifacts\"\x00\x12M\n\x08simulate\x12\x1c.fscompiler.simulation_input\x1a\x1d.fscompiler.simulation_output\"\x00(\x01\x30\x01\x62\x06proto3')



_FQIR = DESCRIPTOR.message_types_by_name['fqir']
_TFLITE = DESCRIPTOR.message_types_by_name['tflite']
_MODEL = DESCRIPTOR.message_types_by_name['model']
_STATUS = DESCRIPTOR.message_types_by_name['status']
_COMPILED_ARTIFACTS = DESCRIPTOR.message_types_by_name['compiled_artifacts']
_NDARRAY = DESCRIPTOR.message_types_by_name['ndarray']
_SIMULATION_DATA = DESCRIPTOR.message_types_by_name['simulation_data']
_SIMULATION_INPUT = DESCRIPTOR.message_types_by_name['simulation_input']
_SIMULATION_OUTPUT = DESCRIPTOR.message_types_by_name['simulation_output']
fqir = _reflection.GeneratedProtocolMessageType('fqir', (_message.Message,), {
  'DESCRIPTOR' : _FQIR,
  '__module__' : 'compiler_service_pb2'
  # @@protoc_insertion_point(class_scope:fscompiler.fqir)
  })
_sym_db.RegisterMessage(fqir)

tflite = _reflection.GeneratedProtocolMessageType('tflite', (_message.Message,), {
  'DESCRIPTOR' : _TFLITE,
  '__module__' : 'compiler_service_pb2'
  # @@protoc_insertion_point(class_scope:fscompiler.tflite)
  })
_sym_db.RegisterMessage(tflite)

model = _reflection.GeneratedProtocolMessageType('model', (_message.Message,), {
  'DESCRIPTOR' : _MODEL,
  '__module__' : 'compiler_service_pb2'
  # @@protoc_insertion_point(class_scope:fscompiler.model)
  })
_sym_db.RegisterMessage(model)

status = _reflection.GeneratedProtocolMessageType('status', (_message.Message,), {
  'DESCRIPTOR' : _STATUS,
  '__module__' : 'compiler_service_pb2'
  # @@protoc_insertion_point(class_scope:fscompiler.status)
  })
_sym_db.RegisterMessage(status)

compiled_artifacts = _reflection.GeneratedProtocolMessageType('compiled_artifacts', (_message.Message,), {
  'DESCRIPTOR' : _COMPILED_ARTIFACTS,
  '__module__' : 'compiler_service_pb2'
  # @@protoc_insertion_point(class_scope:fscompiler.compiled_artifacts)
  })
_sym_db.RegisterMessage(compiled_artifacts)

ndarray = _reflection.GeneratedProtocolMessageType('ndarray', (_message.Message,), {
  'DESCRIPTOR' : _NDARRAY,
  '__module__' : 'compiler_service_pb2'
  # @@protoc_insertion_point(class_scope:fscompiler.ndarray)
  })
_sym_db.RegisterMessage(ndarray)

simulation_data = _reflection.GeneratedProtocolMessageType('simulation_data', (_message.Message,), {
  'DESCRIPTOR' : _SIMULATION_DATA,
  '__module__' : 'compiler_service_pb2'
  # @@protoc_insertion_point(class_scope:fscompiler.simulation_data)
  })
_sym_db.RegisterMessage(simulation_data)

simulation_input = _reflection.GeneratedProtocolMessageType('simulation_input', (_message.Message,), {
  'DESCRIPTOR' : _SIMULATION_INPUT,
  '__module__' : 'compiler_service_pb2'
  # @@protoc_insertion_point(class_scope:fscompiler.simulation_input)
  })
_sym_db.RegisterMessage(simulation_input)

simulation_output = _reflection.GeneratedProtocolMessageType('simulation_output', (_message.Message,), {
  'DESCRIPTOR' : _SIMULATION_OUTPUT,
  '__module__' : 'compiler_service_pb2'
  # @@protoc_insertion_point(class_scope:fscompiler.simulation_output)
  })
_sym_db.RegisterMessage(simulation_output)

_COMPILE = DESCRIPTOR.services_by_name['Compile']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _FQIR._serialized_start=38
  _FQIR._serialized_end=141
  _TFLITE._serialized_start=143
  _TFLITE._serialized_end=214
  _MODEL._serialized_start=216
  _MODEL._serialized_end=301
  _STATUS._serialized_start=303
  _STATUS._serialized_end=341
  _COMPILED_ARTIFACTS._serialized_start=343
  _COMPILED_ARTIFACTS._serialized_end=416
  _NDARRAY._serialized_start=418
  _NDARRAY._serialized_end=456
  _SIMULATION_DATA._serialized_start=458
  _SIMULATION_DATA._serialized_end=563
  _SIMULATION_INPUT._serialized_start=565
  _SIMULATION_INPUT._serialized_end=681
  _SIMULATION_OUTPUT._serialized_start=683
  _SIMULATION_OUTPUT._serialized_end=789
  _COMPILE._serialized_start=792
  _COMPILE._serialized_end=944
# @@protoc_insertion_point(module_scope)
