/*
 Do not modify, auto-generated by model_gen.tcl

 Copyright 2019 Alain Dargelas

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

 http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
 */

/*
 * File:   union_var.h
 * Author:
 *
 * Created on December 14, 2019, 10:03 PM
 */

#ifndef UHDM_UNION_VAR_H
#define UHDM_UNION_VAR_H

#include <uhdm/sv_vpi_user.h>
#include <uhdm/uhdm_vpi_user.h>

#include <uhdm/containers.h>
#include <uhdm/variables.h>




namespace UHDM {
class expr;

class union_var final : public variables {
  UHDM_IMPLEMENT_RTTI(union_var, variables)
public:
  // Implicit constructor used to initialize all members,
  // comment: union_var();
  virtual ~union_var() final = default;

  virtual const BaseClass* VpiParent() const final { return vpiParent_; }

  virtual bool VpiParent(BaseClass* data) final { vpiParent_ = data; return true; }

  virtual bool VpiFile(const std::string& data) final;

  virtual const std::string& VpiFile() const final;

  virtual unsigned int UhdmId() const final { return uhdmId_; }

  virtual bool UhdmId(unsigned int data) final { uhdmId_ = data; return true; }

  bool VpiPackedArrayMember() const { return vpiPackedArrayMember_; }

  bool VpiPackedArrayMember(bool data) { vpiPackedArrayMember_ = data; return true; }

  bool VpiConstantSelect() const { return vpiConstantSelect_; }

  bool VpiConstantSelect(bool data) { vpiConstantSelect_ = data; return true; }

  VectorOfvar_bit* Var_bits() const { return var_bits_; }

  bool Var_bits(VectorOfvar_bit* data) { var_bits_ = data; return true; }

  VectorOfvariables* Variables() const { return variables_; }

  bool Variables(VectorOfvariables* data) { variables_ = data; return true; }

  const expr* Expr_index() const { return expr_index_; }

  bool Expr_index(expr* data) { expr_index_ = data; return true; }

  virtual unsigned int VpiType() const final { return vpiUnionVar; }

  virtual union_var* DeepClone(Serializer* serializer, ElaboratorListener* elaborator, BaseClass* parent) const override;

  virtual const BaseClass* GetByVpiName(std::string_view name) const override;

  virtual std::tuple<const BaseClass*, UHDM_OBJECT_TYPE, const std::vector<const BaseClass*>*> GetByVpiType(int type) const override;

  virtual vpi_property_value_t GetVpiPropertyValue(int property) const override;

  virtual int Compare(const BaseClass* const other, AnySet& visited) const override;

  virtual  UHDM_OBJECT_TYPE UhdmType() const final { return uhdmunion_var; }

protected:
  void DeepCopy(union_var* clone, Serializer* serializer,
                ElaboratorListener* elaborator, BaseClass* parent) const;

private:
  BaseClass* vpiParent_ = nullptr;

  SymbolFactory::ID vpiFile_ = 0;

  unsigned int uhdmId_ = 0;

  bool vpiPackedArrayMember_ = false;

  bool vpiConstantSelect_ = false;

  VectorOfvar_bit* var_bits_ = nullptr;

  VectorOfvariables* variables_ = nullptr;

  expr* expr_index_ = nullptr;
};


typedef FactoryT<union_var> union_varFactory;


typedef FactoryT<std::vector<union_var *>> VectorOfunion_varFactory;

}  // namespace UHDM

#endif
