from multivalidator import cpf
from multivalidator import cnpj
from multivalidator import date
from multivalidator import emails
from multivalidator import fone_number
from multivalidator import passport
from multivalidator import password
from multivalidator import url
from multivalidator import bank_card
from multivalidator import fake_data