
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-03-13T16:56:36-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "11f0daf0f054bff56e8c53888b13d7271c7bb471",
 "version": "0.8.4"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
