
# This file was generated by 'versioneer.py' (0.23) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-03-01T16:39:29-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "371195acb0994b65a336469087e5d91c4a318e3b",
 "version": "23.02.00"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
