FED_OPPORTUNITY_NUMBER = 0
FED_OPPORTUNITY_TITLE = 1
FED_AGENCY_CODE = 2
FED_AGENCY_NAME = 3
FED_ESTIMATED_FUNDING = 4
FED_EXPECTED_NUMBER_OF_AWARDS = 5
FED_GRANTOR_CONTACT = 6
FED_AGENCY_CONTACT_PHONE = 7
FED_AGENCY_CONTACT_EMAIL = 8
FED_ESTIMATED_POST_DATE = 9
FED_ESTIMATED_APPLICATION_DUE_DATE = 10
FED_POSTED_DATE = 11
FED_CLOSE_DATE = 12
FED_LAST_UPDATED_DATE_TIME = 13
FED_VERSION = 14
FED_OPPORTUNITY_STATUS = 15

# Even though the grants.gov CSV file has a 16 fields in the header,
# The data rows have 20 fields 
FED_RESERVED_FIELD_1 = 16
FED_RESERVED_FIELD_2 = 17
FED_RESERVED_FIELD_3 = 18
FED_RESERVED_FIELD_4 = 19

# These fields are added during post processing
FED_LEFT_COLUMN_HTML = 20
FED_RIGHT_COLUMN_HTML = 21
FED_ELIGIBILITY_HTML = 22
FED_ADDITIONAL_INFO_HTML = 23
FED_AWARD_CEIL = 24
FED_AWARD_FLOOR = 25

# Additional reserved fields
# FED_RESERVED_FIELD_5 = 25
FED_ID = 26                         # Primary Key
FED_PIV_FUNDER_URL = 27
FED_DESCRIPTION = 28

# Add field for selection
FED_SELECTION_STATUS = 29

# For some reason, the header only has 16 fields, but the data rows have variable number fields
FED_NUM_FIELDS = 30

FED_ELIGIBILITY = 16

# Field indices for pivot-

PIV_OPPORTUNITY_ID = 0
PIV_TITLE = 1
PIV_INTERNAL_COORD_REQ = 2
PIV_INTERNAL_COORD_NOTE = 3
PIV_FUNDER = 4
PIV_FUNDER_TYPE = 5
PIV_COUNTRY_OF_FUNDER = 6
PIV_RELATED_FUNDER = 7
PIV_CFDA_NUMBERS = 8
PIV_DEADLINE = 9
PIV_MESSAGES = 10
PIV_AMOUNT = 11
PIV_ELIGIBILITY = 12
PIV_APPLICANT_LOC = 13
PIV_CITIZENSHIP = 14
PIV_ACTIVITY_LOC = 15
PIV_APPLICANT_TYPE = 16
PIV_ABSTRACT = 17
PIV_FUNDER_URL = 18
PIV_PIVOT_URL = 19
PIV_KEYWORDS = 20
PIV_FUNDING_TYPE = 21

