# Generated by Django 4.1.4 on 2022-12-13 18:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('oasis', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('date_from', models.DateTimeField(verbose_name='From')),
                ('date_to', models.DateTimeField(verbose_name='To')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Product price')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='oasis.product', verbose_name='Product')),
            ],
        ),
        migrations.AddIndex(
            model_name='price',
            index=models.Index(fields=['product', 'date_from', 'date_to'], name='coffee_pric_product_244c7f_idx'),
        ),
    ]
