# Generated by Django 4.1.5 on 2023-01-18 02:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('oasis', '0002_geographiclocation_typeclient_documenttype_client_and_more'),
        ('coffee_price', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prices', related_query_name='product', to='oasis.product', verbose_name='Product'),
        ),
    ]
