from typing import Any, Callable, Optional

def validate_bool() -> Callable[[Any, bool], bool]: ...
def validate_float(nullable: bool = ..., minimum: Optional[float] = ..., maximum: Optional[float] = ...) -> Callable[[Any, float], float]: ...
def validate_int(nullable: bool = ..., minimum: Optional[int] = ..., maximum: Optional[int] = ..., allowed: Optional[list[int]] = ..., forbidden: Optional[list[int]] = ...) -> Callable[[Any, Optional[int]], Optional[int]]: ...
def validate_str(nullable: bool = ..., min_len: Optional[float] = ..., max_len: Optional[float] = ..., allowed: Optional[list[str]] = ..., regex: Optional[str] = ..., is_numeric: bool = ..., is_directory: bool = ..., is_file: bool = ..., is_date_string: bool = ...) -> Callable[[Any, str], str]: ...
