industries = {
    "A01": "Agriculture",
    "A21": "Baking",
    "A22": "Meat Processing",
    "A23": "Tobacco",
    "A24": "Tobacco",
    "A41": "Fashion",
    "A42": "Fashion",
    "A43": "Fashion",
    "A44": "Fashion",
    "A45": "Fashion",
    "A46": "Fashion",
    "A47": "Furniture",
    "A61": "Medical Science",
    "A62": "Health & Hygiene",
    "A63": "Sports",
    "A99": "Human Necessity",
    "B01": "Chemical Industry",
    "B02": "Grain Processing",
    "B03": "Grain Processing",
    "B04": "Chemical Industry",
    "B05": "Chemical Industry",
    "B06": "Chemical Industry",
    "B07": "Chemical Industry",
    "B08": "Chemical Industry",
    "B09": "Waste Treatment",
    "B21": "Industrial",
    "B22": "Industrial",
    "B23": "Industrial",
    "B24": "Industrial",
    "B25": "Industrial",
    "B26": "Industrial",
    "B27": "Industrial",
    "B28": "Industrial",
    "B29": "Industrial",
    "B30": "Industrial",
    "B31": "Industrial",
    "B32": "Industrial",
    "B33": "Industrial",
    "B41": "Printing",
    "B42": "Industrial",
    "B43": "Industrial",
    "B44": "Industrial",
    "B60": "Vehicles",
    "B61": "Vehicles",
    "B62": "Vehicles",
    "B63": "Vehicles",
    "B64": "Aviation",
    "B65": "Industrial",
    "B66": "Industrial",
    "B67": "Industrial",
    "B68": "Industrial",
    "B81": "Nanotechnology",
    "B82": "Nanotechnology",
    "B99": "Industrial/Transportation",
    "C01": "Inorganic Chemistry",
    "C02": "Water Treatment",
    "C03": "Glass Technology",
    "C04": "Construction Technology",
    "C05": "Fertilisers",
    "C06": "Explosives",
    "C07": "Organic Chemistry",
    "C08": "Organic Chemistry",
    "C09": "Paints & Dyes",
    "C10": "Petrochemical Manufacturing",
    "C11": "Oil & Fat",
    "C12": "Biochemistry",
    "C13": "Sugar Industry",
    "C14": "Leather Products",
    "C21": "Mettalurgy of Iron",
    "C22": "Alloys & Their Product",
    "C23": "Coating Material",
    "C25": "Electrolytic Process",
    "C30": "Crystal Growth",
    "C40": "Combinatorial Technology",
    "C99": "Chemistry & Mettalurgy",
    "D01": "Threads & Fibres",
    "D02": "Yarns",
    "D03": "Weaving",
    "D04": "Braiding",
    "D05": "Sewing",
    "D06": "Treatment of Textiles",
    "D07": "Non Electric Cables",
    "D21": "Paper Making",
    "D99": "Textile/ Paper",
    "E01": "Road/Railway Construction",
    "E02": "Hydraulics",
    "E03": "Water Supplyline",
    "E04": "Building Construction",
    "E05": "Locks & Safes",
    "E06": "Doors & Windows",
    "E21": "Mining",
    "E99": "Construction",
    "F01": "Engines",
    "F02": "Combustion Engines",
    "F03": "Machines & Engines",
    "F04": "Pumps",
    "F15": "Pressure Actuators",
    "F16": "Insulation",
    "F17": "Gas/Liquid Storage",
    "F21": "Lighting",
    "F22": "Steam Generation",
    "F23": "Combustion Process",
    "F24": "Ventilation",
    "F25": "Refrigeration",
    "F26": "Heat Exchange",
    "F27": "Furnaces",
    "F28": "Heat Exchange",
    "F41": "Weapons",
    "F42": "Weapons",
    "F99": "Mechanical Engineering",
    "G01": "Mensuration",
    "G02": "Optics",
    "G03": "Electrography",
    "G04": "Horology",
    "G05": "Physics: Control Aparatus",
    "G06": "Computational Technology",
    "G07": "Checking Device",
    "G08": "Signalling",
    "G09": "Educational Material",
    "G10": "Musical Instrument",
    "G11": "Information Storage",
    "G12": "Scientific Instrument",
    "G16": "Comunication Technology",
    "G21": "Nuclear Technology",
    "G99": "Physics",
    "H01": "Electrical Instruments",
    "H02": "Power Generation",
    "H03": "Electric Circuitry",
    "H04": "Communication Technique",
    "H05": "Communication Technique",
    "H99": "Electricity",
    "Y02": "New Technological Field",
    "Y04": "New Technological Field",
    "Y10": "New Technological Field",
    "P"  : "Plant"
}