from utils import bank_card
from utils import cpf
from utils import cnpj
from utils import date
from utils import emails
from utils import fake_data
from utils import fone_number
from utils import passport
from utils import password
from utils import url