"""Shared examples."""

from .schemas.examples import (  # noqa
    tag_concert,
    tag_theatre,
    all_tags,
    src_tags,
    raw_tags,

    all_market_events,
    src_market_events,
    raw_market_events,
    event_aria,
    event_kipelov_with_classical,

    all_domains,
    src_domains,
    raw_domains,
    domain_spb,
    domain_msk,
    domain_vrn,
    domain_lip,

    all_places,
    src_places,
    raw_places,
    place_msk,
    place_spb,

    all_persons,
    src_persons,
    raw_persons,
    person_kipelov,
    person_dubinin,
    person_radnev,
    person_mae,
    person_emelianenko,
    person_tayson,
    person_zenit,
    person_kerjakov,
    person_mostovoy,
    person_chelsea,
    person_haverz,
    person_silva,

    all_categories,
    src_categories,
    raw_categories,
    category_concert,
    category_theatre,
    category_opera,
    category_rock,
    category_classic,
    category_viola,
    category_guitar,
    category_show,
    category_kids,
    category_standup,
    category_sport,
    category_box,
    category_football,

    all_charts,
    src_charts,
    raw_charts,
    chart_classical,
    chart_rock,
    chart_box,

    all_layouts,
    raw_layouts,
    src_layouts,
    layout_diff,
    layout_default,

    all_locations,
    raw_locations,
    src_locations,
    location_msk,
    location_spb,

    raw_category_view,
)
