# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from th2_grpc_woodpecker import woodpecker_pb2 as th2__grpc__woodpecker_dot_woodpecker__pb2


class WoodpeckerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.start = channel.unary_unary(
                '/woodpecker.Woodpecker/start',
                request_serializer=th2__grpc__woodpecker_dot_woodpecker__pb2.StartRequest.SerializeToString,
                response_deserializer=th2__grpc__woodpecker_dot_woodpecker__pb2.Response.FromString,
                )
        self.schedule = channel.unary_unary(
                '/woodpecker.Woodpecker/schedule',
                request_serializer=th2__grpc__woodpecker_dot_woodpecker__pb2.ScheduleRequest.SerializeToString,
                response_deserializer=th2__grpc__woodpecker_dot_woodpecker__pb2.Response.FromString,
                )
        self.stop = channel.unary_unary(
                '/woodpecker.Woodpecker/stop',
                request_serializer=th2__grpc__woodpecker_dot_woodpecker__pb2.StopRequest.SerializeToString,
                response_deserializer=th2__grpc__woodpecker_dot_woodpecker__pb2.Response.FromString,
                )


class WoodpeckerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def start(self, request, context):
        """starts a load with a constant rate for indefinite amount of time
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def schedule(self, request, context):
        """starts a load with variable rate for a certain amount of time
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def stop(self, request, context):
        """stops current load
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_WoodpeckerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'start': grpc.unary_unary_rpc_method_handler(
                    servicer.start,
                    request_deserializer=th2__grpc__woodpecker_dot_woodpecker__pb2.StartRequest.FromString,
                    response_serializer=th2__grpc__woodpecker_dot_woodpecker__pb2.Response.SerializeToString,
            ),
            'schedule': grpc.unary_unary_rpc_method_handler(
                    servicer.schedule,
                    request_deserializer=th2__grpc__woodpecker_dot_woodpecker__pb2.ScheduleRequest.FromString,
                    response_serializer=th2__grpc__woodpecker_dot_woodpecker__pb2.Response.SerializeToString,
            ),
            'stop': grpc.unary_unary_rpc_method_handler(
                    servicer.stop,
                    request_deserializer=th2__grpc__woodpecker_dot_woodpecker__pb2.StopRequest.FromString,
                    response_serializer=th2__grpc__woodpecker_dot_woodpecker__pb2.Response.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'woodpecker.Woodpecker', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Woodpecker(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def start(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/woodpecker.Woodpecker/start',
            th2__grpc__woodpecker_dot_woodpecker__pb2.StartRequest.SerializeToString,
            th2__grpc__woodpecker_dot_woodpecker__pb2.Response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def schedule(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/woodpecker.Woodpecker/schedule',
            th2__grpc__woodpecker_dot_woodpecker__pb2.ScheduleRequest.SerializeToString,
            th2__grpc__woodpecker_dot_woodpecker__pb2.Response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def stop(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/woodpecker.Woodpecker/stop',
            th2__grpc__woodpecker_dot_woodpecker__pb2.StopRequest.SerializeToString,
            th2__grpc__woodpecker_dot_woodpecker__pb2.Response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
