
# This file was generated by 'versioneer.py' (0.21) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-03-10T15:07:23-0600",
 "dirty": false,
 "error": null,
 "full-revisionid": "4c5abeac3057c55146cd9c5add9d8e22f015882a",
 "version": "0.0.8.dev20230314"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
