# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: th2_grpc_woodpecker/woodpecker.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from th2_grpc_common import common_pb2 as th2__grpc__common_dot_common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n$th2_grpc_woodpecker/woodpecker.proto\x12\nwoodpecker\x1a\x1cth2_grpc_common/common.proto\"y\n\x0cStartRequest\x12\x0c\n\x04rate\x18\x01 \x01(\r\x12\x10\n\x08settings\x18\x02 \x01(\t\x12!\n\x0fparent_event_id\x18\x03 \x01(\x0b\x32\x08.EventID\x12\x10\n\x08tickRate\x18\x04 \x01(\r\x12\x14\n\x0cmaxBatchSize\x18\x05 \x01(\r\"\xd7\x01\n\x0fScheduleRequest\x12\x0e\n\x06\x63ycles\x18\x01 \x01(\r\x12/\n\x05steps\x18\x02 \x03(\x0b\x32 .woodpecker.ScheduleRequest.Step\x12!\n\x0fparent_event_id\x18\x03 \x01(\x0b\x32\x08.EventID\x1a`\n\x04Step\x12\x10\n\x08\x64uration\x18\x01 \x01(\r\x12\x0c\n\x04rate\x18\x02 \x01(\r\x12\x10\n\x08settings\x18\x03 \x01(\t\x12\x10\n\x08tickRate\x18\x04 \x01(\r\x12\x14\n\x0cmaxBatchSize\x18\x05 \x01(\r\"\r\n\x0bStopRequest\"l\n\x08Response\x12+\n\x06status\x18\x01 \x01(\x0e\x32\x1b.woodpecker.Response.Status\x12\x0f\n\x07message\x18\x02 \x01(\t\"\"\n\x06Status\x12\x0b\n\x07SUCCESS\x10\x00\x12\x0b\n\x07\x46\x41ILURE\x10\x01\x32\xbb\x01\n\nWoodpecker\x12\x37\n\x05start\x12\x18.woodpecker.StartRequest\x1a\x14.woodpecker.Response\x12=\n\x08schedule\x12\x1b.woodpecker.ScheduleRequest\x1a\x14.woodpecker.Response\x12\x35\n\x04stop\x12\x17.woodpecker.StopRequest\x1a\x14.woodpecker.ResponseB$\n com.exactpro.th2.woodpecker.grpcP\x01\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'th2_grpc_woodpecker.woodpecker_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n com.exactpro.th2.woodpecker.grpcP\001'
  _STARTREQUEST._serialized_start=82
  _STARTREQUEST._serialized_end=203
  _SCHEDULEREQUEST._serialized_start=206
  _SCHEDULEREQUEST._serialized_end=421
  _SCHEDULEREQUEST_STEP._serialized_start=325
  _SCHEDULEREQUEST_STEP._serialized_end=421
  _STOPREQUEST._serialized_start=423
  _STOPREQUEST._serialized_end=436
  _RESPONSE._serialized_start=438
  _RESPONSE._serialized_end=546
  _RESPONSE_STATUS._serialized_start=512
  _RESPONSE_STATUS._serialized_end=546
  _WOODPECKER._serialized_start=549
  _WOODPECKER._serialized_end=736
# @@protoc_insertion_point(module_scope)
