
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-03-14T18:41:28+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "b8931e6f6cba2a6d4663f57f596d69fc01820068",
 "version": "1.17.16.post0.dev25"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
