/*
 Do not modify, auto-generated by model_gen.tcl

 Copyright 2019 Alain Dargelas

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

 http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
 */

/*
 * File:   class_defn.h
 * Author:
 *
 * Created on December 14, 2019, 10:03 PM
 */

#ifndef UHDM_CLASS_DEFN_H
#define UHDM_CLASS_DEFN_H

#include <uhdm/sv_vpi_user.h>
#include <uhdm/uhdm_vpi_user.h>

#include <uhdm/containers.h>
#include <uhdm/scope.h>




namespace UHDM {
class extends;

class class_defn final : public scope {
  UHDM_IMPLEMENT_RTTI(class_defn, scope)
public:
  // Implicit constructor used to initialize all members,
  // comment: class_defn();
  virtual ~class_defn() final = default;

  virtual const BaseClass* VpiParent() const final { return vpiParent_; }

  virtual bool VpiParent(BaseClass* data) final { vpiParent_ = data; return true; }

  virtual bool VpiFile(const std::string& data) final;

  virtual const std::string& VpiFile() const final;

  virtual unsigned int UhdmId() const final { return uhdmId_; }

  virtual bool UhdmId(unsigned int data) final { uhdmId_ = data; return true; }

  bool VpiVirtual() const { return vpiVirtual_; }

  bool VpiVirtual(bool data) { vpiVirtual_ = data; return true; }

  bool VpiAutomatic() const { return vpiAutomatic_; }

  bool VpiAutomatic(bool data) { vpiAutomatic_ = data; return true; }

  const extends* Extends() const { return extends_; }

  bool Extends(extends* data) { extends_ = data; return true; }

  VectorOftask_func* Task_funcs() const { return task_funcs_; }

  bool Task_funcs(VectorOftask_func* data) { task_funcs_ = data; return true; }

  VectorOfconstraint* Constraints() const { return constraints_; }

  bool Constraints(VectorOfconstraint* data) { constraints_ = data; return true; }

  VectorOfclass_defn* Deriveds() const { return deriveds_; }

  bool Deriveds(VectorOfclass_defn* data) { deriveds_ = data; return true; }

  VectorOfclass_typespec* Class_typespecs() const { return class_typespecs_; }

  bool Class_typespecs(VectorOfclass_typespec* data) { class_typespecs_ = data; return true; }

  virtual unsigned int VpiType() const final { return vpiClassDefn; }

  virtual class_defn* DeepClone(Serializer* serializer, ElaboratorListener* elaborator, BaseClass* parent) const override;

  virtual const BaseClass* GetByVpiName(std::string_view name) const override;

  virtual std::tuple<const BaseClass*, UHDM_OBJECT_TYPE, const std::vector<const BaseClass*>*> GetByVpiType(int type) const override;

  virtual vpi_property_value_t GetVpiPropertyValue(int property) const override;

  virtual int Compare(const BaseClass* const other, AnySet& visited) const override;

  virtual  UHDM_OBJECT_TYPE UhdmType() const final { return uhdmclass_defn; }

protected:
  void DeepCopy(class_defn* clone, Serializer* serializer,
                ElaboratorListener* elaborator, BaseClass* parent) const;

private:
  BaseClass* vpiParent_ = nullptr;

  SymbolFactory::ID vpiFile_ = 0;

  unsigned int uhdmId_ = 0;

  bool vpiVirtual_ = false;

  bool vpiAutomatic_ = false;

  extends* extends_ = nullptr;

  VectorOftask_func* task_funcs_ = nullptr;

  VectorOfconstraint* constraints_ = nullptr;

  VectorOfclass_defn* deriveds_ = nullptr;

  VectorOfclass_typespec* class_typespecs_ = nullptr;
};


typedef FactoryT<class_defn> class_defnFactory;


typedef FactoryT<std::vector<class_defn *>> VectorOfclass_defnFactory;

}  // namespace UHDM

#endif
