/*
 Do not modify, auto-generated by model_gen.tcl

 Copyright 2019 Alain Dargelas

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

 http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
 */

/*
 * File:   tf_call.h
 * Author:
 *
 * Created on December 14, 2019, 10:03 PM
 */

#ifndef UHDM_TF_CALL_H
#define UHDM_TF_CALL_H

#include <uhdm/sv_vpi_user.h>
#include <uhdm/uhdm_vpi_user.h>

#include <uhdm/containers.h>
#include <uhdm/expr.h>

#include "tf_call_args.h"


namespace UHDM {
class scope;

class tf_call : public expr {
  UHDM_IMPLEMENT_RTTI(tf_call, expr)
public:
  // Implicit constructor used to initialize all members,
  // comment: tf_call();
  virtual ~tf_call() = default;

  const scope* Scope() const { return scope_; }

  bool Scope(scope* data) { scope_ = data; return true; }

  VectorOfany* Tf_call_args() const { return tf_call_args_; }

  bool Tf_call_args(VectorOfany* data) { if (!tf_call_argsGroupCompliant(data)) return false; tf_call_args_ = data; return true; }

  virtual bool VpiName(const std::string& data) final;

  virtual const std::string& VpiName() const final;

  virtual tf_call* DeepClone(Serializer* serializer, ElaboratorListener* elaborator, BaseClass* parent) const override = 0;

  virtual const BaseClass* GetByVpiName(std::string_view name) const override;

  virtual std::tuple<const BaseClass*, UHDM_OBJECT_TYPE, const std::vector<const BaseClass*>*> GetByVpiType(int type) const override;

  virtual vpi_property_value_t GetVpiPropertyValue(int property) const override;

  virtual int Compare(const BaseClass* const other, AnySet& visited) const override;

  virtual  UHDM_OBJECT_TYPE UhdmType() const override { return uhdmtf_call; }

protected:
  void DeepCopy(tf_call* clone, Serializer* serializer,
                ElaboratorListener* elaborator, BaseClass* parent) const;

private:
  scope* scope_ = nullptr;

  VectorOfany* tf_call_args_ = nullptr;

  SymbolFactory::ID vpiName_ = 0;
};

#if 0 // This class cannot be instantiated
typedef FactoryT<tf_call> tf_callFactory;
#endif

typedef FactoryT<std::vector<tf_call *>> VectorOftf_callFactory;

}  // namespace UHDM

#endif
