
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-03-15T13:47:22+0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "4198760cf6b7648580981ba717a9d32dbcd9bfe5",
 "version": "4.16.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
