
# This file was generated by 'versioneer.py' (0.23) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-03-14T05:24:17+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "62491e09a7bf8e9ac33ba62f59fd06aa4e51e850",
 "version": "1.18.2.post0.dev204"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
