
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-03-17T13:17:50-0700",
 "dirty": true,
 "error": null,
 "full-revisionid": "7a38f6e17d2308586ed0c39beff5ec5a6884b93d",
 "version": "v0.0.4"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
