
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-03-13T14:26:16-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "a93ec79aba14ca96222ada621fed9b5e1b5cfcbd",
 "version": "2.1.1.post0.dev18"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
