/*
 Do not modify, auto-generated by model_gen.tcl

 Copyright 2019 Alain Dargelas

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

 http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
 */

/*
 * File:   gen_scope_array.h
 * Author:
 *
 * Created on December 14, 2019, 10:03 PM
 */

#ifndef UHDM_GEN_SCOPE_ARRAY_H
#define UHDM_GEN_SCOPE_ARRAY_H

#include <uhdm/sv_vpi_user.h>
#include <uhdm/uhdm_vpi_user.h>

#include <uhdm/containers.h>
#include <uhdm/BaseClass.h>

#include "interf_prog_mod_group.h"


namespace UHDM {
class gen_var;

class gen_scope_array final : public BaseClass {
  UHDM_IMPLEMENT_RTTI(gen_scope_array, BaseClass)
public:
  // Implicit constructor used to initialize all members,
  // comment: gen_scope_array();
  virtual ~gen_scope_array() final = default;

  virtual const BaseClass* VpiParent() const final { return vpiParent_; }

  virtual bool VpiParent(BaseClass* data) final { vpiParent_ = data; return true; }

  virtual bool VpiFile(const std::string& data) final;

  virtual const std::string& VpiFile() const final;

  virtual unsigned int UhdmId() const final { return uhdmId_; }

  virtual bool UhdmId(unsigned int data) final { uhdmId_ = data; return true; }

  int VpiSize() const { return vpiSize_; }

  bool VpiSize(int data) { vpiSize_ = data; return true; }

  virtual bool VpiName(const std::string& data) final;

  virtual const std::string& VpiName() const final;

  bool VpiFullName(const std::string& data);

  const std::string& VpiFullName() const;

  const gen_var* Gen_var() const { return gen_var_; }

  bool Gen_var(gen_var* data) { gen_var_ = data; return true; }

  VectorOfgen_scope* Gen_scopes() const { return gen_scopes_; }

  bool Gen_scopes(VectorOfgen_scope* data) { gen_scopes_ = data; return true; }

  const any* VpiInstance() const { return vpiInstance_; }

  bool VpiInstance(any* data) { if (!interf_prog_mod_groupGroupCompliant(data)) return false; vpiInstance_ = data; return true; }

  virtual unsigned int VpiType() const final { return vpiGenScopeArray; }

  virtual gen_scope_array* DeepClone(Serializer* serializer, ElaboratorListener* elaborator, BaseClass* parent) const override;

  virtual const BaseClass* GetByVpiName(std::string_view name) const override;

  virtual std::tuple<const BaseClass*, UHDM_OBJECT_TYPE, const std::vector<const BaseClass*>*> GetByVpiType(int type) const override;

  virtual vpi_property_value_t GetVpiPropertyValue(int property) const override;

  virtual int Compare(const BaseClass* const other, AnySet& visited) const override;

  virtual  UHDM_OBJECT_TYPE UhdmType() const final { return uhdmgen_scope_array; }

protected:
  void DeepCopy(gen_scope_array* clone, Serializer* serializer,
                ElaboratorListener* elaborator, BaseClass* parent) const;

private:
  BaseClass* vpiParent_ = nullptr;

  SymbolFactory::ID vpiFile_ = 0;

  unsigned int uhdmId_ = 0;

  int vpiSize_ = 0;

  SymbolFactory::ID vpiName_ = 0;

  SymbolFactory::ID vpiFullName_ = 0;

  gen_var* gen_var_ = nullptr;

  VectorOfgen_scope* gen_scopes_ = nullptr;

  any* vpiInstance_ = nullptr;
};


typedef FactoryT<gen_scope_array> gen_scope_arrayFactory;


typedef FactoryT<std::vector<gen_scope_array *>> VectorOfgen_scope_arrayFactory;

}  // namespace UHDM

#endif
