/*
 Do not modify, auto-generated by model_gen.tcl

 Copyright 2019 Alain Dargelas

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

 http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
 */

/*
 * File:   part_select.h
 * Author:
 *
 * Created on December 14, 2019, 10:03 PM
 */

#ifndef UHDM_PART_SELECT_H
#define UHDM_PART_SELECT_H

#include <uhdm/sv_vpi_user.h>
#include <uhdm/uhdm_vpi_user.h>

#include <uhdm/containers.h>
#include <uhdm/expr.h>

#include "actual_group.h"


namespace UHDM {
class expr;

class part_select final : public expr {
  UHDM_IMPLEMENT_RTTI(part_select, expr)
public:
  // Implicit constructor used to initialize all members,
  // comment: part_select();
  virtual ~part_select() final = default;

  virtual const BaseClass* VpiParent() const final { return vpiParent_; }

  virtual bool VpiParent(BaseClass* data) final { vpiParent_ = data; return true; }

  virtual bool VpiFile(const std::string& data) final;

  virtual const std::string& VpiFile() const final;

  virtual unsigned int UhdmId() const final { return uhdmId_; }

  virtual bool UhdmId(unsigned int data) final { uhdmId_ = data; return true; }

  bool VpiConstantSelect() const { return vpiConstantSelect_; }

  bool VpiConstantSelect(bool data) { vpiConstantSelect_ = data; return true; }

  const expr* Left_range() const { return left_range_; }

  bool Left_range(expr* data) { left_range_ = data; return true; }

  const expr* Right_range() const { return right_range_; }

  bool Right_range(expr* data) { right_range_ = data; return true; }

  const any* Actual_group() const { return actual_group_; }

  bool Actual_group(any* data) { if (!actual_groupGroupCompliant(data)) return false; actual_group_ = data; return true; }

  virtual unsigned int VpiType() const final { return vpiPartSelect; }

  virtual part_select* DeepClone(Serializer* serializer, ElaboratorListener* elaborator, BaseClass* parent) const override;

  virtual const BaseClass* GetByVpiName(std::string_view name) const override;

  virtual std::tuple<const BaseClass*, UHDM_OBJECT_TYPE, const std::vector<const BaseClass*>*> GetByVpiType(int type) const override;

  virtual vpi_property_value_t GetVpiPropertyValue(int property) const override;

  virtual int Compare(const BaseClass* const other, AnySet& visited) const override;

  virtual  UHDM_OBJECT_TYPE UhdmType() const final { return uhdmpart_select; }

protected:
  void DeepCopy(part_select* clone, Serializer* serializer,
                ElaboratorListener* elaborator, BaseClass* parent) const;

private:
  BaseClass* vpiParent_ = nullptr;

  SymbolFactory::ID vpiFile_ = 0;

  unsigned int uhdmId_ = 0;

  bool vpiConstantSelect_ = false;

  expr* left_range_ = nullptr;

  expr* right_range_ = nullptr;

  any* actual_group_ = nullptr;
};


typedef FactoryT<part_select> part_selectFactory;


typedef FactoryT<std::vector<part_select *>> VectorOfpart_selectFactory;

}  // namespace UHDM

#endif
