
# This file was generated by 'versioneer.py' (0.28) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-03-14T16:03:39+0900",
 "dirty": false,
 "error": null,
 "full-revisionid": "aa610a120f2216a8d5c146d71cf56bcbe34c36dc",
 "version": "0.1.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
