
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-03-17T23:09:09+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "ccefc28afd3a5e42909e65a6c69beb4e6e9163b2",
 "version": "2.0.28"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
