VERSION_YEAR = 2023
VERSION_MONTH = int('03')
VERSION_DAY = int('14')
VERSION_HOUR = int('02')
VERSION_MINUTE = int('38')
MAJOR_VERSION = 1
MINOR_VERSION = 0
PATCH_VERSION = 202303140238
version_date = '2023/03/14 02:38'
version = '{}.{}.{}'.format(MAJOR_VERSION, MINOR_VERSION, PATCH_VERSION)
__all__  = ['MAJOR_VERSION', 'MINOR_VERSION', 'PATCH_VERSION', 'version_date', 'version']
