
# This file was generated by 'versioneer.py' (0.28) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-03-07T21:10:44+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "f8e5410865354074ed7d0e939a7dab21cd5b05a4",
 "version": "0.5.9.dev20230314"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
