
# This file was generated by 'versioneer.py' (0.28) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-03-15T14:15:39+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "0eb0e22920ab5bd3f35eddfa64eb70fd447d709c",
 "version": "2.1.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
