sectors = {
'A01B' : 'Soil working in agriculture or forestry',
'A01C' : 'Planting',
'A01D' : 'Harvesting',
'A01F' : 'Processing of harvested produce',
'A01G' : 'Horticulture',
'A01H' : 'New plants or {non-transgenic} processes for obtaining them',
'A01J' : 'Manufacture of dairy products ',
'A01K' : 'Animal husbandry',
'A01L' : 'Shoeing of animals',
'A01M' : 'Catching, trapping or scaring of animals ',
'A01N' : 'Preservation of bodies of humans or animals or plants or parts thereof ',
'A01P' : 'Biocidal, pest repellant, pest attractant or plant growth regulatory activity of chemical compounds or preparations',
'A21B' : 'Bakers ovens',
'A21C' : 'Machines or equipment for making or processing doughs',
'A21D' : 'Treatment, e.g. preservation, of flour or dough, e.g. by addition of materials',
'A22B' : 'Slaughtering',
'A22C' : 'Processing meat, poultry, or fish ',
'A23B' : 'Preserving, e.g. by canning, meat, fish, eggs, fruit, vegetables, edible seeds',
'A23C' : 'Dairy products, e.g. milk, butter, cheese',
'A23D' : 'Edible oils or fats, e.g. margarines, shortenings, cooking oils ',
'A23F' : 'Coffee',
'A23G' : 'Cocoa',
'A23J' : 'Protein compositions for foodstuffs',
'A23K' : 'Fodder',
'A23L' : 'Foods, foodstuffs, or non-alcoholic beverages, not covered by subclasses a23bâ -â a23j',
'A23N' : 'Machines or apparatus for treating harvested fruit, vegetables or flower bulbs in bulk, not otherwise provided for',
'A23P' : 'Shaping or working of foodstuffs, not fully covered by a single other subclass',
'A23V' : 'Indexing scheme relating to foods, foodstuffs or non-alcoholic beverages',
'A23Y' : 'Indexing scheme relating to lactic or propionic acid bacteria used in foodstuffs or food preparation',
'A24B' : 'Manufacture or preparation of tobacco for smoking or chewing',
'A24C' : 'Machines for making cigars or cigarettes',
'A24D' : 'Cigars',
'A24F' : 'Smokers requisites',
'A41B' : 'Shirts',
'A41C' : 'Corsets',
'A41D' : 'Outerwear',
'A41F' : 'Garment fastenings',
'A41G' : 'Artificial flowers',
'A41H' : 'Appliances or methods for making clothes, e.g. for dress-making, for tailoring, not otherwise provided for ',
'A42B' : 'Hats',
'A42C' : 'Manufacturing or trimming head coverings, e.g. hats',
'A43B' : 'Characteristic features of footwear',
'A43C' : 'Fastenings or attachments of footwear',
'A43D' : 'Machines, tools, equipment or methods for manufacturing or repairing footwear',
'A44B' : 'Buttons, pins, buckles, slide fasteners, or the like ',
'A44C' : 'Personal adornments, e.g. jewellery',
'A44D' : 'Indexing scheme relating to buttons, pins, buckles or slide fasteners, and to jewellery, bracelets or other personal adornments',
'A45B' : 'Walking sticks ',
'A45C' : 'Purses',
'A45D' : 'Hairdressing or shaving equipment ',
'A45F' : 'Travelling or camp equipment: sacks or packs carried on the body',
'A46B' : 'Brushes ',
'A46D' : 'Manufacture of brushes',
'A47B' : 'Tables',
'A47C' : 'Chairs ',
'A47D' : 'Furniture specially adapted for children ',
'A47F' : 'Special furniture, fittings, or accessories for shops, storehouses, bars, restaurants or the like',
'A47G' : 'Household or table equipment ',
'A47H' : 'Furnishings for windows or doors ',
'A47J' : 'Kitchen equipment',
'A47K' : 'Sanitary equipment not otherwise provided for ',
'A47L' : 'Domestic washing or cleaning ',
'A61B' : 'Diagnosis',
'A61C' : 'Dentistry',
'A61D' : 'Veterinary instruments, implements, tools, or methods',
'A61F' : 'Filters implantable into blood vessels',
'A61G' : 'Transport, personal conveyances, or accommodation specially adapted for patients or disabled persons ',
'A61H' : 'Physical therapy apparatus, e.g. devices for locating or stimulating reflex points in the body',
'A61J' : 'Containers specially adapted for medical or pharmaceutical purposes',
'A61K' : 'Preparations for medical, dental, or toilet purposes ',
'A61L' : 'Methods or apparatus for sterilising materials or objects in general',
'A61M' : 'Devices for introducing media into, or onto, the body ',
'A61N' : 'Electrotherapy',
'A61P' : 'Specific therapeutic activity of chemical compounds or medicinal preparations',
'A61Q' : 'Specific use of cosmetics or similar toilet preparations',
'A62B' : 'Devices, apparatus or methods for life-saving ',
'A62C' : 'Fire-fighting ',
'A62D' : 'Chemical means for extinguishing fires or for combating or protecting against harmful chemical agents',
'A63B' : 'Apparatus for physical training, gymnastics, swimming, climbing, or fencing',
'A63C' : 'Skates',
'A63D' : 'Bowling games, e.g. skittles, bocce or bowls',
'A63F' : 'Card, board, or roulette games',
'A63G' : 'Merry-go-rounds',
'A63H' : 'Toys, e.g. tops, dolls, hoops or building blocks',
'A63J' : 'Devices for theatres, circuses, or the like',
'A63K' : 'Racing',
'A99Z' : 'Subject matter not otherwise provided for in this section',
'B01B' : 'Boiling',
'B01D' : 'Separation ',
'B01F' : 'Mixing, e.g. dissolving, emulsifying, dispersing ',
'B01J' : 'Chemical or physical processes, e.g. catalysis or colloid chemistry',
'B01L' : 'Chemical or physical laboratory apparatus for general use ',
'B02B' : 'Preparing grain for milling',
'B02C' : 'Crushing, pulverising, or disintegrating in general',
'B03B' : 'Separating solid materials using liquids or using pneumatic tables or jigs ',
'B03C' : 'Magnetic or electrostatic separation of solid materials from solid materials or fluids',
'B03D' : 'Flotation',
'B04B' : 'Centrifuges ',
'B04C' : 'Apparatus using free vortex flow, e.g. cyclones ',
'B05B' : 'Spraying apparatus',
'B05C' : 'Apparatus for applying fluent materials to surfaces, in general ',
'B05D' : 'Processes for applying fluent materials to surfaces, in general ',
'B06B' : 'Methods or apparatus for generating or transmitting mechanical vibrations of infrasonic, sonic, or ultrasonic frequency, {e.g.} for performing mechanical work in general ',
'B07B' : 'Separating solids from solids by sieving, screening, sifting or by using gas currents',
'B07C' : 'Postal sorting',
'B08B' : 'Cleaning in general',
'B09B' : 'Disposal of solid waste',
'B09C' : 'Reclamation of contaminated soil ',
'B21B' : 'Rolling of metal ',
'B21C' : 'Manufacture of metal sheets, wire, rods, tubes or profiles, otherwise than by rolling',
'B21D' : 'Working or processing of sheet metal or metal tubes, rods or profiles without essentially removing material',
'B21F' : 'Working or processing of metal wire ',
'B21G' : 'Making needles, pins or nails of metal',
'B21H' : 'Making particular metal objects by rolling, e.g. screws, wheels, rings, barrels, balls ',
'B21J' : 'Forging',
'B21K' : 'Making forged or pressed metal products, e.g. horse-shoes, rivets, bolts or wheels ',
'B21L' : 'Making metal chains ',
'B22C' : 'Foundry moulding ',
'B22D' : 'Casting of metals',
'B22F' : 'Working metallic powder',
'B23B' : 'Turning',
'B23C' : 'Milling ',
'B23D' : 'Planing',
'B23F' : 'Making gears or toothed racks ',
'B23G' : 'Thread cutting',
'B23H' : 'Working of metal by the action of a high concentration of electric current on a workpiece using an electrode which takes the place of a tool',
'B23K' : 'Soldering or unsoldering',
'B23P' : 'Metal-working not otherwise provided for',
'B23Q' : 'Details, components, or accessories for machine tools, e.g. arrangements for copying or controlling ',
'B24B' : 'Machines, devices, or processes for grinding or polishing ',
'B24C' : 'Abrasive or related blasting with particulate material',
'B24D' : 'Tools for grinding, buffing or sharpening ',
'B25B' : 'Tools or bench devices not otherwise provided for, for fastening, connecting, disengaging or holding',
'B25C' : 'Hand-held nailing or stapling tools',
'B25D' : 'Percussive tools {}',
'B25F' : 'Combination or multi-purpose tools not otherwise provided for',
'B25G' : 'Handles for hand implements ',
'B25H' : 'Workshop equipment, e.g. for marking-out work',
'B25J' : 'Manipulators',
'B26B' : 'Hand-held cutting tools not otherwise provided for ',
'B26D' : 'Cutting',
'B26F' : 'Perforating',
'B27B' : 'Saws for wood or similar material',
'B27C' : 'Planing, drilling, milling, turning or universal machines for wood or similar material ',
'B27D' : 'Working veneer or plywood ',
'B27F' : 'Dovetailed work',
'B27G' : 'Accessory machines or apparatus for working wood or similar materials',
'B27H' : 'Bending wood or similar material',
'B27J' : 'Mechanical working of cane, cork, or similar materials',
'B27K' : 'Processes, apparatus or selection of substances for impregnating, staining, dyeing, bleaching of wood or similar materials, or treating of wood or similar materials with permeant liquids, not otherwise provided for ',
'B27L' : 'Removing bark or vestiges of branches ',
'B27M' : 'Working of wood not provided for in subclasses b27bâ -â b27l',
'B27N' : 'Manufacture by dry processes of articles, with or without organic binding agents, made from particles or fibres consisting of wood or other lignocellulosic or like organic material ',
'B28B' : 'Shaping clay or other ceramic compositions',
'B28C' : 'Preparing clay',
'B28D' : 'Working stone or stone-like materials',
'B29B' : 'Preparation or pretreatment of the material to be shaped',
'B29C' : 'Shaping or joining of plastics',
'B29D' : 'Producing particular articles from plastics or from substances in a plastic state ',
'B29K' : 'Indexing scheme associated with subclasses b29b, b29c or b29d, relating to moulding materials or to materials for {moulds, } reinforcements, fillers or preformed parts, e.g. inserts',
'B29L' : 'Indexing scheme associated with subclass b29c, relating to particular articles',
'B30B' : 'Presses in general {}',
'B31B' : 'Making containers of paper, cardboard or material worked in a manner analogous to paper ',
'B31C' : 'Making wound articles, e.g. wound tubes, of paper, cardboard or material worked in a manner analogous to paper',
'B31D' : 'Making articles of paper, cardboard or material worked in a manner analogous to paper, not provided for in subclasses b31b or b31c ',
'B31F' : 'Mechanical working or deformation of paper, cardboard or material worked in a manner analogous to paper ',
'B32B' : 'Layered products, i.e. products built-up of strata of flat or non-flat, e.g. cellular or honeycomb, form',
'B33Y' : 'Additive manufacturing, i.e. manufacturing of three-dimensional  objects by additive deposition, additive agglomeration or additive layering, e.g. by 3-d printing, stereolithography or selective laser sintering',
'B41B' : 'Machines or accessories for making, setting, or distributing type',
'B41C' : 'Processes for the manufacture or reproduction of printing surfaces ',
'B41D' : 'Apparatus for the mechanical reproduction of printing surfaces for stereotype printing',
'B41F' : 'Printing machines or presses ',
'B41G' : 'Apparatus for bronze printing, line printing, or for bordering or edging sheets or like articles',
'B41J' : 'Typewriters',
'B41K' : 'Stamps',
'B41L' : 'Apparatus or devices for manifolding, duplicating or printing for office or other commercial purposes',
'B41M' : 'Printing, duplicating, marking, or copying processes',
'B41N' : 'Printing plates or foils ',
'B41P' : 'Indexing scheme relating to printing, lining machines, typewriters, and to stamps',
'B42B' : 'Permanently attaching together sheets, quires or signatures or permanently attaching objects thereto ',
'B42C' : 'Bookbinding ',
'B42D' : 'Books',
'B42F' : 'Sheets temporarily attached together',
'B42P' : 'Indexing scheme relating to books, filing appliances or the like',
'B43K' : 'Implements for writing or drawing ',
'B43L' : 'Articles for writing or drawing upon',
'B43M' : 'Bureau accessories not otherwise provided for ',
'B44B' : 'Machines, apparatus or tools for artistic work, e.g. for sculpturing, guilloching, carving, branding, inlaying ',
'B44C' : 'Producing decorative effects ',
'B44D' : 'Painting or artistic drawing, not otherwise provided for',
'B44F' : 'Special designs or pictures',
'B60B' : 'Vehicle wheels ',
'B60C' : 'Vehicle tyres',
'B60D' : 'Vehicle connections ',
'B60F' : 'Vehicles for use both on rail and on road',
'B60G' : 'Vehicle suspension arrangements ',
'B60H' : 'Arrangements of heating, cooling, ventilating or other air-treating devices specially adapted for passenger or goods spaces of vehicles',
'B60J' : 'Windows, windscreens, non-fixed roofs, doors, or similar devices for vehicles',
'B60K' : 'Arrangement or mounting of propulsion units or of transmissions in vehicles',
'B60L' : 'Propulsion of electrically-propelled vehicles ',
'B60M' : 'Power supply lines, and devices along rails, for electrically- propelled vehicles ',
'B60N' : 'Seats specially adapted for vehicles',
'B60P' : 'Vehicles adapted for load transportation or to transport, to carry, or to comprise special loads or objects ',
'B60Q' : 'Arrangement of signalling or lighting devices, the mounting or supporting thereof or circuits therefor, for vehicles in general',
'B60R' : 'Vehicles, vehicle fittings, or vehicle parts, not otherwise provided for',
'B60S' : 'Servicing, cleaning, repairing, supporting, lifting, or manoeuvring of vehicles, not otherwise provided for',
'B60T' : 'Vehicle brake control systems or parts thereof',
'B60V' : 'Air-cushion vehicles',
'B60W' : 'Conjoint control of vehicle sub-units of different type or different function',
'B60Y' : 'Indexing scheme relating to aspects cross-cutting vehicle technology',
'B61B' : 'Railway systems',
'B61C' : 'Locomotives',
'B61D' : 'Body details or kinds of railway vehicles ',
'B61F' : 'Rail vehicle suspensions, e.g. underframes, bogies or arrangements of wheel axles',
'B61G' : 'Couplings',
'B61H' : 'Brakes or other retarding devices specially adapted for rail vehicles',
'B61J' : 'Shifting or shunting of rail vehicles ',
'B61K' : 'Auxiliary equipment specially adapted for railways, not otherwise provided for ',
'B61L' : 'Guiding railway traffic',
'B62B' : 'Hand-propelled vehicles, e.g. hand carts or perambulators',
'B62C' : 'Vehicles drawn by animals',
'B62D' : 'Motor vehicles',
'B62H' : 'Cycle stands',
'B62J' : 'Cycle saddles or seats',
'B62K' : 'Cycles',
'B62L' : 'Brakes specially adapted for cycles {}',
'B62M' : 'Rider propulsion of wheeled vehicles or sledges',
'B63B' : 'Ships or other waterborne vessels',
'B63C' : 'Launching, hauling-out, or dry-docking of vessels',
'B63G' : 'Offensive or defensive arrangements on vessels',
'B63H' : 'Marine propulsion or steering ',
'B63J' : 'Auxiliaries on vessels',
'B64B' : 'Lighter-than air aircraft',
'B64C' : 'Aeroplanes',
'B64D' : 'Equipment for fitting in or to aircraft',
'B64F' : 'Ground or aircraft-carrier-deck installations specially adapted for use in connection with aircraft',
'B64G' : 'Cosmonautics',
'B65B' : 'Machines, apparatus or devices for, or methods of, packaging articles or materials',
'B65C' : 'Labelling or tagging machines, apparatus, or processes {}',
'B65D' : 'Containers for storage or transport of articles or materials, e.g. bags, barrels, bottles, boxes, cans, cartons, crates, drums, jars, tanks, hoppers, forwarding containers',
'B65F' : 'Gathering or removal of domestic or like refuse ',
'B65G' : 'Transport or storage devices, e.g. conveyors for loading or tipping,â shop conveyor systems orâ pneumatic tube conveyors ',
'B65H' : 'Handling thin or filamentary material, e.g. sheets, webs, cables',
'B66B' : 'Elevators',
'B66C' : 'Cranes',
'B66D' : 'Capstans',
'B66F' : 'Hoisting, lifting, hauling or pushing, not otherwise provided for, e.g. devices which apply a lifting or pushing force directly to the surface of a load ',
'B67B' : 'Applying closure members to bottles jars, or similar containers',
'B67C' : 'Cleaning, filling with liquids or semiliquids, or emptying, of bottles, jars, cans, casks, barrels, or similar containers, not otherwise provided for',
'B67D' : 'Dispensing, delivering or transferring liquids, not otherwise provided for ',
'B68B' : 'Harness',
'B68C' : 'Saddles',
'B68F' : 'Making articles from leather, canvas, or the like',
'B68G' : 'Methods, equipment, or machines for use in upholstering',
'B81B' : 'Microstructural devices or systems, e.g. micromechanical devices ',
'B81C' : 'Processes or apparatus specially adapted for the manufacture or treatment of microstructural devices or systems ',
'B82B' : 'Nanostructures formed by manipulation of individual atoms, molecules, or limited collections of atoms or molecules as discrete units',
'B82Y' : 'Specific uses or applications of nanostructures',
'B99Z' : 'Subject matter not otherwise provided for in this section',
'C01B' : 'Non-metallic elements',
'C01C' : 'Ammonia',
'C01D' : 'Compounds of alkali metals, i.e. lithium, sodium, potassium, rubidium, caesium, or francium ',
'C01F' : 'Compounds of the metals beryllium, magnesium, aluminium, calcium, strontium, barium, radium, thorium, or of the rare-earth metals ',
'C01G' : 'Compounds containing metals not covered by subclasses c01d or c01f ',
'C01P' : 'Indexing scheme relating to structural and physical aspects of solid inorganic compounds',
'C02F' : 'Treatment of water, waste water, sewage, or sludge ',
'C03B' : 'Manufacture, shaping, or supplementary processes',
'C03C' : 'Chemical composition of glasses, glazes or vitreous enamels',
'C04B' : 'Lime, magnesia',
'C05B' : 'Phosphatic fertilisers',
'C05C' : 'Nitrogenous fertilisers',
'C05D' : 'Inorganic fertilisers not covered by subclasses c05b, c05c',
'C05F' : 'Organic fertilisers not covered by subclasses c05b, c05c, e.g. fertilisers from waste or refuse {}',
'C05G' : 'Mixtures of fertilisers covered individually by different subclasses of class c05',
'C06B' : 'Explosives or thermic compositions ',
'C06C' : 'Detonating or priming devices',
'C06D' : 'Means for generating smoke or mist',
'C06F' : 'Matches',
'C07B' : 'General methods of organic chemistry',
'C07C' : 'Acyclic or carbocyclic compounds',
'C07D' : 'Heterocyclic compounds',
'C07F' : 'Acyclic, carbocyclic or heterocyclic compounds containing elements other than carbon, hydrogen, halogen, oxygen, nitrogen, sulfur, selenium or tellurium ',
'C07G' : 'Compounds of unknown constitution',
'C07H' : 'Sugars',
'C07J' : 'Steroids ',
'C07K' : 'Peptides ',
'C08B' : 'Polysaccharides',
'C08C' : 'Treatment or chemical modification of rubbers',
'C08F' : 'Macromolecular compounds obtained by reactions only involving carbon-to-carbon unsaturated bonds',
'C08G' : 'Macromolecular compounds obtained otherwise than by reactions only involving unsaturated carbon-to-carbon bonds',
'C08H' : 'Derivatives of natural macromolecular compounds ',
'C08J' : 'Working-up',
'C08K' : 'Use of inorganic or non-macromolecular organic substances as compounding ingredients ',
'C08L' : 'Compositions of macromolecular compounds ',
'C09B' : 'Organic dyes or closely-related compounds for producing dyes {, e.g. pigments}',
'C09C' : 'Treatment of inorganic materials, other than fibrous fillers, to enhance their pigmenting or filling properties ',
'C09D' : 'Coating compositions, e.g. paints, varnishes or lacquers',
'C09F' : 'Natural resins',
'C09G' : 'Polishing compositions ',
'C09H' : 'Preparation of glue or gelatine',
'C09J' : 'Adhesives',
'C09K' : 'Materials for miscellaneous applications, not provided for elsewhere',
'C10B' : 'Destructive distillation of carbonageous materials for production of gas, coke, tar, or similar materials ',
'C10C' : 'Working-up pitch, asphalt, bitumen, tar',
'C10F' : 'Drying or working-up of peat',
'C10G' : 'Cracking hydrocarbon oils',
'C10H' : 'Production of acetylene by wet methods {}',
'C10J' : 'Production of producer gas, water-gas, synthesis gas from solid carbonaceous material, or mixtures containing these gases ',
'C10K' : 'Purifying or modifying the chemical composition of combustible gases containing carbon monoxide',
'C10L' : 'Fuels not otherwise provided for ',
'C10M' : 'Lubricating compositions ',
'C10N' : 'Indexing scheme associated with subclass c10m relating to lubricating compositions',
'C11B' : 'Producing, e.g. by pressing raw materials or by extraction from waste materials, refining or preserving fats, fatty substances, e.g. lanolin, fatty oils or waxes',
'C11C' : 'Fatty acids from fats, oils or waxes',
'C11D' : 'Detergent compositions ',
'C12C' : 'Beer',
'C12F' : 'Recovery of by-products of fermented solutions ',
'C12G' : 'Wine',
'C12H' : 'Pasteurisation, sterilisation, preservation, purification, clarification or ageing of alcoholic beverages',
'C12J' : 'Vinegar',
'C12L' : 'Pitching or depitching machines',
'C12M' : 'Apparatus for enzymology or microbiology',
'C12N' : 'Microorganisms or enzymes',
'C12P' : 'Fermentation or enzyme-using processes to synthesise a desired chemical compound or composition or to separate optical isomers from a racemic mixture {}',
'C12Q' : 'Measuring or testing processes involving enzymes, nucleic acids or microorganisms ',
'C12R' : 'Indexing scheme associated with subclasses c12c - c12q, relating to microorganisms',
'C12Y' : 'Enzymes',
'C13B' : 'Production of sucrose',
'C13K' : 'Saccharides obtained from natural sources or by hydrolysis of naturally occurring disaccharides, oligosaccharides or polysaccharides ',
'C14B' : 'Mechanical treatment or processing of skins, hides or leather in general',
'C14C' : 'Chemical treatment of hides, skins or leather, e.g. tanning, impregnating, finishing',
'C21B' : 'Manufacture of iron or steel ',
'C21C' : 'Processing of pig-iron, e.g. refining, manufacture of wrought-iron or steel',
'C21D' : 'Modifying the physical structure of ferrous metals',
'C22B' : 'Production and refining of metals ',
'C22C' : 'Alloys ',
'C22F' : 'Changing the physical structure of non-ferrous metals and non-ferrous alloys ',
'C23C' : 'Coating metallic material',
'C23D' : 'Enamelling of, or applying a vitreous layer to, metals ',
'C23F' : 'Non-mechanical removal of metallic material from surface ',
'C23G' : 'Cleaning or degreasing of metallic material by chemical methods other than electrolysis ',
'C25B' : 'Electrolytic or electrophoretic processes for the production of compounds or non-metals',
'C25C' : 'Processes for the electrolytic production, recovery or refining of metals',
'C25D' : 'Processes for the electrolytic or electrophoretic production of coatings',
'C25F' : 'Processes for the electrolytic removal of materials from objects',
'C30B' : 'Single-crystal-growth ',
'C40B' : 'Combinatorial chemistry',
'C99Z' : 'Subject matter not otherwise provided for in this section',
'D01B' : 'Mechanical treatment of natural fibrous or filamentary material to obtain fibres of filaments, e.g. for spinning ',
'D01C' : 'Chemical treatment of natural filamentary or fibrous material to obtain filaments or fibres for spinning',
'D01D' : 'Mechanical methods or apparatus in the manufacture of artificial filaments, threads, fibres, bristles or ribbons',
'D01F' : 'Chemical features in the manufacture of artificial filaments, threads, fibres, bristles or ribbons',
'D01G' : 'Preliminary treatment of fibres, e.g. for spinning ',
'D01H' : 'Spinning or twisting ',
'D02G' : 'Crimping or curling fibres, filaments, threads, or yarns',
'D02H' : 'Warping, beaming or leasing',
'D02J' : 'Finishing or dressing of filaments, yarns, threads, cords, ropes or the like ',
'D03C' : 'Shedding mechanisms',
'D03D' : 'Woven fabrics',
'D03J' : 'Auxiliary weaving apparatus',
'D04B' : 'Knitting',
'D04C' : 'Braiding or manufacture of lace, including bobbin-net or carbonised lace',
'D04D' : 'Trimmings',
'D04G' : 'Making nets by knotting of filamentary material',
'D04H' : 'Making textile fabrics, e.g. from fibres or filamentary material ',
'D05B' : 'Sewing ',
'D05C' : 'Embroidering',
'D05D' : 'Indexing scheme associated with subclasses d05b and d05c, relating to sewing, embroidering and tufting',
'D06B' : 'Treating textile materials using liquids, gases or vapours ',
'D06C' : 'Finishing, dressing, tentering or stretching textile fabrics',
'D06F' : 'Laundering, drying, ironing, pressing or folding textile articles',
'D06G' : 'Mechanical or pressure cleaning of carpets, rugs, sacks, hides, or other skin or textile articles or fabrics',
'D06H' : 'Marking, inspecting, seaming or severing textile materials ',
'D06J' : 'Pleating, kilting or goffering textile fabrics or wearing apparel ',
'D06L' : 'Dry-cleaning, washing or bleaching fibres, filaments, threads, yarns, fabrics, feathers or made-up fibrous goods',
'D06M' : 'Treatment, not provided for elsewhere in class d06, of fibres, threads, yarns, fabrics, feathers or fibrous goods made from such materials',
'D06N' : 'Wall, floor, or like covering materials, e.g. linoleum, oilcloth, artificial leather, roofing felt, consisting of a fibrous web coated with a layer of macromolecular material',
'D06P' : 'Dyeing or printing textiles',
'D06Q' : 'Decorating textiles ',
'D07B' : 'Ropes or cables in general ',
'D10B' : 'Indexing scheme associated with sublasses of section d, relating to textiles',
'D21B' : 'Fibrous raw materials or their mechanical treatment',
'D21C' : 'Production of cellulose by removing non-cellulose substances from cellulose-containing materials',
'D21D' : 'Treatment of the materials before passing to the paper-making machine',
'D21F' : 'Paper-making machines',
'D21G' : 'Calenders',
'D21H' : 'Pulp compositions',
'D21J' : 'Fibreboard',
'D99Z' : 'Subject matter not otherwise provided for in this section',
'E01B' : 'Permanent way',
'E01C' : 'Construction of, or surfaces for, roads, sports grounds, or the like',
'E01D' : 'Construction of bridges, {elevated roadways} or viaducts',
'E01F' : 'Additional work, such as equipping roads or the construction of platforms, helicopter landing stages, signs, snow fences, or the like',
'E01H' : 'Street cleaning',
'E02B' : 'Hydraulic engineering ',
'E02C' : 'Ship-lifting devices or mechanisms',
'E02D' : 'Foundations',
'E02F' : 'Dredging',
'E03B' : 'Installations or methods for obtaining, collecting, or distributing water ',
'E03C' : 'Domestic plumbing installations for fresh water or waste water ',
'E03D' : 'Water-closets or urinals with flushing devices',
'E03F' : 'Sewers',
'E04B' : 'General building constructions',
'E04C' : 'Structural elements',
'E04D' : 'Roof coverings',
'E04F' : 'Finishing work on buildings, e.g. stairs, floors ',
'E04G' : 'Scaffolding',
'E04H' : 'Buildings or like structures for particular purposes',
'E05B' : 'Locks',
'E05C' : 'Bolts or fastening devices for wings, specially for doors or windows ',
'E05D' : 'Hinges or suspension devices for doors, windows or wings ',
'E05F' : 'Devices for moving wings into open or closed position',
'E05G' : 'Safes or strong-rooms for valuables',
'E05Y' : 'Indexing scheme relating to hinges or other suspension devices for doors, windows or wings and devices for moving wings into open or closed position, checks for wings and wing fittings not otherwise provided for, concerned with the functioning of the wing',
'E06B' : 'Fixed or movable closures for openings in buildings, vehicles, fences or like enclosures in general, e.g. doors, windows, blinds, gates ',
'E06C' : 'Ladders ',
'E21B' : 'Earth drilling, e.g. deep drilling ',
'E21C' : 'Mining or quarrying',
'E21D' : 'Shafts',
'E21F' : 'Safety devices, transport, filling-up, rescue, ventilation, or draining in or of mines or tunnels',
'E99Z' : 'Subject matter not otherwise provided for in this section',
'F01B' : 'Machines or engines, in general or of positive-displacement type, e.g. steam engines ',
'F01C' : 'Rotary-piston or oscillating-piston machines or engines ',
'F01D' : 'Non-positive displacement machines or engines, e.g. steam turbines ',
'F01K' : 'Steam engine plants',
'F01L' : 'Cyclically operating valves for machines or engines',
'F01M' : 'Lubricating of machines or engines in general',
'F01N' : 'Gas-flow silencers or exhaust apparatus for machines or engines in general',
'F01P' : 'Cooling of machines or engines in general',
'F02B' : 'Internal-combustion piston engines',
'F02C' : 'Gas-turbine plants',
'F02D' : 'Controlling combustion engines ',
'F02F' : 'Cylinders, pistons or casings, for combustion engines',
'F02G' : 'Hot gas or combustion-product positive-displacement engine plants ',
'F02K' : 'Jet-propulsion plants ',
'F02M' : 'Supplying combustion engines in general with combustible mixtures or constituents thereof',
'F02N' : 'Starting of combustion engines',
'F02P' : 'Ignition, other than compression ignition, for internal-combustion engines',
'F03B' : 'Machines or engines for liquids ',
'F03C' : 'Positive-displacement engines driven by liquids ',
'F03D' : 'Wind motors',
'F03G' : 'Spring, weight, inertia or like motors',
'F03H' : 'Producing a reactive propulsive thrust, not otherwise provided for ',
'F04B' : 'Positive-displacement machines for liquids',
'F04C' : 'Rotary-piston, or oscillating-piston, positive-displacement machines for liquids ',
'F04D' : 'Non-positive-displacement pumps ',
'F04F' : 'Pumping of fluid by direct contact of another fluid or by using inertia of fluid to be pumped {}',
'F05B' : 'Indexing scheme relating to wind, spring, weight, inertia or like motors, to machines or engines for liquids covered by subclasses f03b, f03d and f03g',
'F05C' : 'Indexing scheme relating to materials, material properties or material characteristics for machines, engines or pumps other than non-positive-displacement machines or engines',
'F05D' : 'Indexing scheme for aspects relating to non-positive-displacement machines or engines, gas-turbines or jet-propulsion plants',
'F15B' : 'Systems acting by means of fluids in general',
'F15C' : 'Fluid-circuit elements predominantly used for computing or control purposes ',
'F15D' : 'Fluid dynamics, i.e. methods or means for influencing the flow of gases or liquids ',
'F16B' : 'Devices for fastening or securing constructional elements or machine parts together, e.g. nails, bolts, circlips, clamps, clips, wedges, joints or jointing ',
'F16C' : 'Shafts',
'F16D' : 'Couplings for transmitting rotation',
'F16F' : 'Springs',
'F16G' : 'Belts, cables, or ropes, predominantly used for driving purposes',
'F16H' : 'Gearing',
'F16J' : 'Pistons {}',
'F16K' : 'Valves',
'F16L' : 'Pipes',
'F16M' : 'Frames, casings or beds of engines, machines or apparatus, not specific to engines, machines or apparatus provided for elsewhere',
'F16N' : 'Lubricating',
'F16P' : 'Safety devices in general',
'F16S' : 'Constructional elements in general',
'F16T' : 'Steam traps or like apparatus for draining-off liquids from enclosures predominantly containing gases or vapours',
'F17B' : 'Gas-holders of variable capacity ',
'F17C' : 'Vessels for containing or storing compressed, liquefied or solidified gases',
'F17D' : 'Pipe-line systems',
'F21H' : 'Incandescent mantles',
'F21K' : 'Non-electric light sources using luminescence',
'F21L' : 'Lighting devices or systems thereof, being portable or specially adapted for transportation',
'F21S' : 'Non-portable lighting devices',
'F21V' : 'Functional features or details of lighting devices or systems thereof',
'F21W' : 'Indexing scheme associated with subclasses f21k, f21l, f21s and f21v, relating to uses or applications of lighting devices or systems',
'F21Y' : 'Indexing scheme associated with subclasses f21k, f21l, f21s and f21v, relating to the form or the kind of the light sources or of the colour of the light emitted',
'F22B' : 'Methods of steam generation',
'F22D' : 'Preheating, or accumulating preheated, feed-water for steam generation',
'F22G' : 'Superheating of steam ',
'F23B' : 'Methods or apparatus for combustion using only solid fuel ',
'F23C' : 'Methods orâ apparatusâ forâ combustionâ usingâ fluidâ fuel or solid fuel suspended inâ  {a carrier gas or} airâ  ',
'F23D' : 'Burners',
'F23G' : 'Cremation furnaces',
'F23H' : 'Grates ',
'F23J' : 'Removal or treatment of combustion products or combustion residues',
'F23K' : 'Feeding fuel to combustion apparatus ',
'F23L' : 'Supplying air or non-combustible liquids or gases to combustion apparatus in generalâ  ',
'F23M' : 'Casings, linings, walls or doors specially adapted for combustion chambers, e.g. firebridges',
'F23N' : 'Regulating or controlling combustion ',
'F23Q' : 'Ignition ',
'F23R' : 'Generating combustion products of high pressure or high velocity, e.g. gas-turbine combustion chambers ',
'F24B' : 'Domestic stoves or ranges for solid fuels ',
'F24C' : 'Domestic stoves or rangesâ  ',
'F24D' : 'Domestic- or space-heating systems, e.g. central heating systems',
'F24F' : 'Air-conditioning',
'F24H' : 'Fluid heaters, e.g. water or air heaters, having heat generating means, in general ',
'F24S' : 'Solar heat collectors',
'F24T' : 'Geothermal collectors',
'F24V' : 'Collection, production or use of heat not otherwise provided for',
'F25B' : 'Refrigeration machines, plants or systems',
'F25C' : 'Producing, working or handling ice',
'F25D' : 'Refrigerators',
'F25J' : 'Liquefaction, solidification or separation of gases or gaseous {or liquefied gaseous} mixtures by pressure and cold treatment {or by bringing them into the supercritical state }',
'F26B' : 'Drying solid materials or objects by removing liquid therefrom ',
'F27B' : 'Furnaces, kilns, ovens, or retorts in general',
'F27D' : 'Details or accessories of furnaces, kilns, ovens, or retorts, in so far as they are of kinds occurring in more than one kind of furnace ',
'F27M' : 'Indexing scheme relating to aspects of the charges or furnaces, kilns, ovens or retorts',
'F28B' : 'Steam or vapour condensers ',
'F28C' : 'Heat-exchange apparatus, not provided for in another subclass, in which the heat-exchange media come into direct contact without chemical interaction ',
'F28D' : 'Heat-exchange apparatus, not provided for in another subclass, in which the heat-exchange media do not come into direct contact ',
'F28F' : 'Details of heat-exchange and heat-transfer apparatus, of general application ',
'F28G' : 'Cleaning of internal or external surfaces of heat-exchange or heat-transfer conduits, e.g. water tubes or boilers ',
'F41A' : 'Functional features or details common to both smallarms and ordnance, e.g. cannons',
'F41B' : 'Weapons for projecting missiles without use of explosive or combustible propellant charge',
'F41C' : 'Smallarms, e.g. pistols, rifles ',
'F41F' : 'Apparatus for launching projectiles or missiles from barrels, e.g. cannons ',
'F41G' : 'Weapon sights',
'F41H' : 'Armour',
'F41J' : 'Targets',
'F42B' : 'Explosive charges, e.g. for blasting, fireworks, ammunition ',
'F42C' : 'Ammunition fuzes ',
'F42D' : 'Blasting ',
'F99Z' : 'Subject matter not otherwise provided for in this section',
'G01B' : 'Measuring length, thickness or similar linear dimensions',
'G01C' : 'Measuring distances, levels or bearings',
'G01D' : 'Measuring not specially adapted for a specific variable',
'G01F' : 'Measuring volume, volume flow, mass flow or liquid level',
'G01G' : 'Weighing ',
'G01H' : 'Measurement of mechanical vibrations or ultrasonic, sonic or infrasonic waves',
'G01J' : 'Measurement of intensity, velocity, spectral content, polarisation, phase or pulse characteristics of infra-red, visible or ultra-violet light',
'G01K' : 'Measuring temperature',
'G01L' : 'Measuring force, stress, torque, work, mechanical power, mechanical efficiency, or fluid pressure ',
'G01M' : 'Testing static or dynamic balance of machines or structures',
'G01N' : 'Investigating or analysing materials by determining their chemical or physical properties ',
'G01P' : 'Measuring linear or angular speed, acceleration, deceleration, or shock',
'G01Q' : 'Scanning-probe techniques or apparatus',
'G01R' : 'Measuring electric variables',
'G01S' : 'Radio direction-finding',
'G01T' : 'Measurement of nuclear or x-radiation ',
'G01V' : 'Geophysics',
'G01W' : 'Meteorology ',
'G02B' : 'Optical elements, systems, or apparatus ',
'G02C' : 'Spectacles',
'G02F' : 'Devices or arrangements, the optical operation of which is modified by changing the optical properties of the medium of the devices or arrangements for the control of the intensity, colour, phase, polarisation or direction of light, e.g. switching, gating, modulating or demodulating',
'G03B' : 'Apparatus or arrangements for taking photographs or for projecting or viewing them',
'G03C' : 'Photosensitive materials for photographic purposes ',
'G03D' : 'Apparatus for processing exposed photographic materials ',
'G03F' : 'Photomechanical production of textured or patterned surfaces, e.g. for printing, for processing of semiconductor devices',
'G03G' : 'Electrography',
'G03H' : 'Holographic processes or apparatus ',
'G04B' : 'Mechanically-driven clocks or watches',
'G04C' : 'Electromechanical clocks or watches ',
'G04D' : 'Apparatus or tools specially designed for making or maintaining clocks or watches',
'G04F' : 'Time-interval measuring ',
'G04G' : 'Electronic time-pieces',
'G04R' : 'Radio-controlled time-pieces',
'G05B' : 'Control or regulating systems in general',
'G05D' : 'Systems for controlling or regulating non-electric variables ',
'G05F' : 'Systems for regulating electric or magnetic variables ',
'G05G' : 'Control devices or systems insofar as characterised by mechanical features only ',
'G06C' : 'Digital computers in which all the computation is effected mechanically ',
'G06D' : 'Digital fluid-pressure computing devices',
'G06E' : 'Optical computing devices',
'G06F' : 'Electric digital data processing ',
'G06G' : 'Analogue computers ',
'G06J' : 'Hybrid computing arrangements ',
'G06K' : 'Recognition of data',
'G06M' : 'Counting mechanisms',
'G06N' : 'Computer systems based on specific computational models',
'G06Q' : 'Data processing systems or methods, specially adapted for administrative, commercial, financial, managerial, supervisory or forecasting purposes',
'G06T' : 'Image data processing or generation, in general',
'G07B' : 'Ticket-issuing apparatus',
'G07C' : 'Time or attendance registers',
'G07D' : 'Handling of coins or valuable papers, e.g. testing, sorting by denominations, counting, dispensing, changing or depositing',
'G07F' : 'Coin-freed or like apparatus ',
'G07G' : 'Registering the receipt of cash, valuables, or tokens ',
'G08B' : 'Signalling or calling systems',
'G08C' : 'Transmission systems for measured values, control or similar signals ',
'G08G' : 'Traffic control systems ',
'G09B' : 'Educational or demonstration appliances',
'G09C' : 'Ciphering or deciphering apparatus for cryptographic or other purposes involving the need for secrecy',
'G09D' : 'Railway or like time or fare tables',
'G09F' : 'Displaying',
'G09G' : 'Arrangements or circuits for control of indicating devices using static means to present variable information ',
'G10B' : 'Organs, harmoniums or similar wind musical instruments with associated blowing apparatus ',
'G10C' : 'Pianos, harpsichords, spinets or similar stringed musical instruments with one or more keyboards ',
'G10D' : 'Stringed musical instruments',
'G10F' : 'Automatic musical instruments ',
'G10G' : 'Representation of music',
'G10H' : 'Electrophonic musical instruments ',
'G10K' : 'Sound-producing devices ',
'G10L' : 'Speech analysis or synthesis',
'G11B' : 'Information storage based on relative movement between record carrier and transducer ',
'G11C' : 'Static stores ',
'G12B' : 'Constructional details of instruments, or comparable details of other apparatus, not otherwise provided for',
'G16B' : 'Bioinformatics, i.e. information and communication technology  specially adapted for genetic or protein-related data processing in computational molecular biology',
'G16C' : 'Computational chemistry',
'G16H' : 'Healthcare informatics, i.e. information and communication technology  specially adapted for the handling or processing of medical or healthcare data',
'G16Y' : 'Information and communication technology specially adapted for the internet of things ',
'G16Z' : 'Information and communication technology  specially adapted for specific application fields, not otherwise provided for',
'G21B' : 'Fusion reactors ',
'G21C' : 'Nuclear reactors ',
'G21D' : 'Nuclear power plant',
'G21F' : 'Protection against x-radiation, gamma radiation, corpuscular radiation or particle bombardment',
'G21G' : 'Conversion of chemical elements',
'G21H' : 'Obtaining energy from radioactive sources',
'G21J' : 'Nuclear explosives',
'G21K' : 'Techniques for handling particles or ionising radiation not otherwise provided for',
'G99Z' : 'Subject matter not otherwise provided for in this section',
'H01B' : 'Cables',
'H01C' : 'Resistors',
'H01F' : 'Magnets',
'H01G' : 'Capacitors',
'H01H' : 'Electric switches',
'H01J' : 'Electric discharge tubes or discharge lamps ',
'H01K' : 'Electric incandescent lamps ',
'H01L' : 'Semiconductor devices',
'H01M' : 'Processes or means, e.g. batteries, for the direct conversion of chemical energy into electrical energy',
'H01P' : 'Waveguides',
'H01Q' : 'Antennas, i.e. radio aerials ',
'H01R' : 'Electrically-conductive connections',
'H01S' : 'Devices using the process of light amplification by stimulated emission of radiation  to amplify or generate light',
'H01T' : 'Spark gaps',
'H02B' : 'Boards, substations, or switching arrangements for the supply or distribution of electric power ',
'H02G' : 'Installation of electric cables or lines, or of combined optical and electric cables or lines ',
'H02H' : 'Emergency protective circuit arrangements ',
'H02J' : 'Circuit arrangements or systems for supplying or distributing electric power',
'H02K' : 'Dynamo-electric machines ',
'H02M' : 'Apparatus for conversion between ac and ac, between ac and dc, or between dc and dc, and for use with mains or similar power supply systems',
'H02N' : 'Electric machines not otherwise provided for',
'H02P' : 'Control or regulation of electric motors, electric generators or dynamo-electric converters',
'H02S' : 'Generation of electric power by conversion of infra-red radiation, visible light or ultraviolet light, e.g. using photovoltaic  modules ',
'H03B' : 'Generation of oscillations, directly or by frequency-changing, by circuits employing active elements which operate in a non-switching manner',
'H03C' : 'Modulation ',
'H03D' : 'Demodulation or transference of modulation from one carrier to another ',
'H03F' : 'Amplifiers ',
'H03G' : 'Control of amplification ',
'H03H' : 'Impedance networks, e.g. resonant circuits',
'H03J' : 'Tuning resonant circuits',
'H03K' : 'Pulse technique ',
'H03L' : 'Automatic control, starting, synchronisation, or stabilisation of generators of electronic oscillations or pulses ',
'H03M' : 'Coding',
'H04B' : 'Transmission',
'H04H' : 'Broadcast communication ',
'H04J' : 'Multiplex communication ',
'H04K' : 'Secret communication',
'H04L' : 'Transmission of digital information, e.g. telegraphic communication ',
'H04M' : 'Telephonic communication ',
'H04N' : 'Pictorial communication, e.g. television',
'H04Q' : 'Selecting ',
'H04R' : 'Loudspeakers, microphones, gramophone pick-ups or like acoustic electromechanical transducers',
'H04S' : 'Stereophonic systemsâ',
'H04T' : 'Indexing scheme relating to standards for electric communication technique ',
'H04W' : 'Wireless communication networks ',
'H05B' : 'Electric heating',
'H05C' : 'Electric circuits or apparatus specially designed for use in equipment for killing, stunning, or guiding living beings ',
'H05F' : 'Static electricity',
'H05G' : 'X-ray technique ',
'H05H' : 'Plasma technique ',
'H05K' : 'Printed circuits',
'H99Z' : 'Subject matter not otherwise provided for in this section',
'Y02A' : 'Technologies for adaptation to climate change',
'Y02B' : 'Climate change mitigation technologies related to buildings, e.g. housing, house appliances or related end-user applications',
'Y02C' : 'Capture, storage, sequestration or disposal of greenhouse gases ',
'Y02D' : 'Climate change mitigation technologies in information and communication technologies , i.e. information and communication technologies aiming at the reduction of their own energy use',
'Y02E' : 'Reduction of greenhouse gas  emissions, related to energy generation, transmission or distribution',
'Y02P' : 'Climate change mitigation technologies in the production or processing of goods',
'Y02T' : 'Climate change mitigation technologies related to transportation',
'Y02W' : 'Climate change mitigation technologies related to wastewater treatment or waste management',
'Y04S' : 'Systems integrating technologies related to power network operation, communication or information technologies for improving the electrical power generation, transmission, distribution, management or usage, i.e. smart grids',
'Y10S' : 'Technical subjects covered by former uspc cross-reference art collections  and digests',
'Y10T' : 'Technical subjects covered by former us classification',

}