
# This file was generated by 'versioneer.py' (0.20) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-03-16T14:18:20-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "b23e9f62ed4c4f8ede0a68c838b97047124926a8",
 "version": "0.3.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
