
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-03-17T14:24:18-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "e4919a1a6ca440b20c569c4683b627a1abaaa298",
 "version": "1.4.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
