# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_core.ipynb.

# %% auto 0
__all__ = ['random_user']

# %% ../nbs/00_core.ipynb 3
import requests

def random_user(gender:str,       # gênero do usuário que será aleatoriamente criado
                nationality:str,  # nacionalidade do usuário que será aleatoriamente criado
):
    "Função que retorna um usuário aleatório da API randomuser.me"
    
    params_dict = {'gender': gender, 'nationality': nationality}
    response = requests.get("https://randomuser.me/api", params=params_dict)
    return response.json()['results'][0]
