# Generated by Django 3.2.18 on 2023-03-14 07:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("nautobot_dns_records", "0002_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="addressrecord",
            name="ttl",
            field=models.IntegerField(
                default=3600,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(604800),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="cnamerecord",
            name="ttl",
            field=models.IntegerField(
                default=3600,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(604800),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="locrecord",
            name="ttl",
            field=models.IntegerField(
                default=3600,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(604800),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="ptrrecord",
            name="ttl",
            field=models.IntegerField(
                default=3600,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(604800),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="sshfprecord",
            name="ttl",
            field=models.IntegerField(
                default=3600,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(604800),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="txtrecord",
            name="ttl",
            field=models.IntegerField(
                default=3600,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(604800),
                ],
            ),
        ),
    ]
