
# This file was generated by 'versioneer.py' (0.21) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-03-08T14:23:58+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "21a5269dbdaadfbc662218cb9bf91184e771e094",
 "version": "1.2.7"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
