# Generated by Django 4.1.3 on 2023-03-13 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credential', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='credential',
            name='subject_did',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
    ]
