# Generated by Django 4.1.3 on 2023-03-15 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('credential', '0002_credential_subject_did'),
    ]

    operations = [
        migrations.CreateModel(
            name='CredentialBlockChainRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('register_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(max_length=200)),
                ('network', models.CharField(max_length=200)),
                ('credential', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='credential.credential')),
            ],
        ),
    ]
