
# This file was generated by 'versioneer.py' (0.22) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-03-17T14:32:36-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "e4d1c274129d2e1ff0287ade895625f633b9c640",
 "version": "1.8.7"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
