# Generated by Django 4.1.3 on 2023-03-16 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credential', '0003_credentialblockchainregister'),
    ]

    operations = [
        migrations.AddField(
            model_name='credentialblockchainregister',
            name='tx_hash',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
