
# This file was generated by 'versioneer.py' (0.26) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-03-17T09:12:58-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "a58e42dcbe705fc18bfdae4b2120c878d706df35",
 "version": "1.11.1-dev.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
