
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-03-15T23:19:32+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "f0ddc110551dd83b4b40bf158fd90f278bca61dd",
 "version": "1.1.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
