
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-03-14T13:36:22-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "ed2ab21d342d409abe45a3b70a7bcdc0f0d3985b",
 "version": "2.9.8.post0.dev2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
