
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-03-14T16:23:34+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "f0c72a3621d6ad1e4f7d6ce8250f61400d7090ef",
 "version": "2.8.3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
