
# This file was generated by 'versioneer.py' (0.28) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-03-16T22:24:10+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "55870621810380f1d5d5fd28d194834f84f3ce0b",
 "version": "4.19"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
