
# This file was generated by 'versioneer.py' (0.28) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-03-14T22:38:42+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "fb06b8b2b12b90a2ca5e79d3bfa4515bd22ca318",
 "version": "1.0.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
