
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-03-17T16:04:10+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "bc8a863e8f50d0fb2f6c6c32fa282d3d43d0fa8a",
 "version": "4.1.81"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
